version: '2.3'

services:
  tidb0:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./log/tidb0:/log
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - --log-file=/log/tidb.log
    restart: on-failure
